Working

diff --git a/functions/install_functions b/functions/install_functions
--- a/functions/install_functions
+++ b/functions/install_functions
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+# Wrap function to disable if WITHOUT_GUI is set to 1
+
+function no_gui() {
+	if [[ $WITHOUT_GUI = 1 ]]; then
+		eval ${2:-"return"}
+	else 
+		eval $1
+	fi
+}
+
 # Install single package function
 #
 # ${1} = Name
@@ -25,10 +35,10 @@ function install_package() {
 			${3}
 		else
 			# Cancelled
-			echo_message info "Installation of ${1} cancelled."
+			 echo_message info "Installation of ${1} cancelled."
 			# return
 			${3}
-		fi
+		fi 
 	else
 		# Already installed
 		echo_message info "Package '${2}' is already installed."
@@ -98,13 +108,8 @@ function install_from_list() {
 	echo_message title "Starting installation of ${1}..."
 	# Variables
 	LIST=$(dirname "$0")'/data/'${2}'.list'
-	# Draw window
-	if (eval `resize` && whiptail \
-		--title "Install ${2^}" \
-		--yesno "Current list of packages that will be installed: \n\n$(cat ${LIST}) \n\nWould you like to proceed?" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
-		--scrolltext \
-		3>&1 1>&2 2>&3) then
+	echo "------------------------$WITHOUT_GUI"
+	if [[ $WITHOUT_GUI = 1 ]]; then
 		# Install loop
 		for PACKAGE in $(cat $LIST); do
 			# If package is not installed
@@ -124,12 +129,40 @@ function install_from_list() {
 		done
 		# Finished
 		echo_message success "Installation of ${1} complete."
-		whiptail --title "Finished" --msgbox "Installation of ${1} is complete." 8 56
-		${3}
 	else
-		# Cancelled
-		echo_message info "Installation of ${1} cancelled."
-		${3}
+		# Draw window
+		if (eval `resize` && whiptail \
+			--title "Install ${2^}" \
+			--yesno "Current list of packages that will be installed: \n\n$(cat ${LIST}) \n\nWould you like to proceed?" \
+			$LINES $COLUMNS $(( $LINES - 12 )) \
+			--scrolltext \
+			3>&1 1>&2 2>&3) then
+			# Install loop
+			for PACKAGE in $(cat $LIST); do
+				# If package is not installed
+				if [ $(check_package_installed $PACKAGE) != 0 ]; then
+					# Install package
+					echo_message warning "Package '$PACKAGE' is not installed. Installing..."
+					# Admin privileges
+					superuser_do "apt install -y $PACKAGE"
+					# Check if failed
+					if [[ $? != 0 ]]; then
+						echo_message error "Error installing '$PACKAGE'."
+					fi
+				else
+					# Show already installed message
+					echo_message info "Package '$PACKAGE' is installed."
+				fi
+			done
+			# Finished
+			echo_message success "Installation of ${1} complete."
+			whiptail --title "Finished" --msgbox "Installation of ${1} is complete." 8 56
+			${3}
+		else
+			# Cancelled
+			echo_message info "Installation of ${1} cancelled."
+			${3}
+		fi
 	fi
 }
 
